[pytest]

; tells pytest which Django settings to use.
DJANGO_SETTINGS_MODULE = config.settings
; only files starting with test_ are considered tests.
python_files = test_*.py
; only search inside our apps/ directory.
testpaths = apps