# Generated by Django 6.0.6 on 2026-06-26 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this file was uploaded to the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this file was last updated')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
