# Generated by Django 4.2.26 on 2026-07-03 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this file was uploaded to the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this file was last updated')),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
