# Generated by Django 4.2.26 on 2026-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
