# Generated by Django 4.2.26 on 2026-07-10 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this file was uploaded to the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When this file was last updated')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
